### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cryptoyacin**
We have just created the GRAPES token which will be at the center of the wwwine ecosystem!

### CODE REVIEW

**Comment by SeverMM** [comment]
Hello, the names of the files are wrong, please use info.txt, logo.png, logo.svg

Thanks.

**Comment by cryptoyacin** [comment]
Hello ,

Thank you for the first validations!
Do you have any idea how long it takes for the final validation for the information to go up on the token page ? :)

**Review by tricastor — APPROVED** [review]
Looks good !

**Review by jszatanek — APPROVED** [review]
no issue to me ! ready to merge

**Review by stephaneLeroy — APPROVED** [review]

**Comment by tricastor** [comment]
Hi @SeverMM , is there something wrong with this PR ? thank you for your help !

**Comment by Samuel-www** [comment]
Hello @SeverMM , any problems with the logo? Please let us know because it's been a while since the validation is pending. Thank you in advance

**Review by tricastor — APPROVED** [review]

**Comment by cryptoyacin** [comment]
Hello @SeverMM,
We have been waiting for more than 3 months for a validation and we see several projects that have their tokens validated.
Is there a problem with our request?
We are looking forward to your feedback so we can make the necessary arrangements if needed.

**Comment by cryptoyacin** [comment]
Hello @SeverMM , We have been waiting for months for the $GRAPES token to be validated and today you close it without giving us any indication. Can you at least give us a feedback so that we can make the necessary changes?

**Comment by SeverMM** [comment]
Thanks for resubmitting, solved

**Pull request closed without merging**
