### PR TITLE
add token DEADBROS-388e63 v2

### PR DESCRIPTION
**Pull request by dotmobo**
Hi,

Here the token DEADBROS-388e63 of our following project : https://www.deadbrothers.club/
I put the devnet version of the token too.

We have now +857 holders of our tokens and +2k followers on twitter.

Thanks for you help

Regards

Morgan

### CODE REVIEW

**Review by SeverMM — APPROVED** [review]
Welcome. Make sure to also brand your NFT collection. It's the same process, just use collection ID instead of token ID.

**Review by SeverMM — CHANGES_REQUESTED** [review]
Oops, file size too large. Please try sticking to the guidelines.

**Comment by dotmobo** [comment]
ok thanks, we will do that changes as soon as possible!

**Comment by dotmobo** [comment]
So i uploaded new logo to respect the guidelines:
- png are 200x200 under 100kb
- svg are under 100kb

I added nft community project folder too in mainnet : DEADBROS-bf822f

Thanks

**Pull request closed without merging**
