### PR TITLE
Updated logo for BPCT Token

### PR DESCRIPTION
**Pull request by macbenouze**

### CODE REVIEW

**Comment by jszatanek** [comment]
Ok, the json validation job fails on another token (EARTH), this change looks ok

**Comment by jszatanek** [comment]
Issue fixed in PR #148

**Comment by jszatanek** [comment]
Now that PR #148 is merged, this one should be ok...

**Review by jszatanek — APPROVED** [review]

**Comment by arelrond** [comment]
This change was approved in another PR.

Closing this one.

**Pull request closed without merging**
