### PR TITLE
Adding GOLDEN logo and information

### PR DESCRIPTION
**Pull request by PaulHendi**

### CODE REVIEW

**Comment by arelrond** [comment]
Hello @PaulHendi - schema.json should be info.json.

Please follow the steps here: https://docs.elrond.com/developers/esdt-tokens/#branding

Once you edit the name and it is properly formatted, please commit the changes and we will review.

Thank you!

**Comment by PaulHendi** [comment]
Thank you @arelrond for your feedback, the file has been renamed :)

**Review by arelrond — APPROVED** [review]

**Comment by PaulHendi** [comment]
Hello @arelrond :)
Is it everything okay now ?
Thanks :)

**Review by arelrond — APPROVED** [review]

**Review by arelrond — APPROVED** [review]

**Comment by PaulHendi** [comment]
Yes ! Thanks for approving again and again, and for your patience :)
I finally understood, after multiple tries..

**Pull request merged**
