### PR TITLE
Branding JOY-43bad3

### PR DESCRIPTION
**Pull request by elrondangels**
Hi Team, 
If you can add a Ledger signature as well, would be great. 
Thank you.

### CODE REVIEW

**Review by SeverMM — APPROVED** [review]

**Comment by elrondangels** [comment]
Hi Sever, 
I replaced the .svg file with an optimized one, so all checks should pass now. 
Thank you very much for your approval.

**Comment by AlexandruPislariu** [comment]
Hello!
Please check our updated [documentation](https://github.com/ElrondNetwork/assets#introduction) and upload files according to it.

**Comment by elrondangels** [comment]
Hello! 
I have updated everything accordingly to the documentation. 
Apologies for ton of commits; it took a while to accommodate all request. 
One recommendation - You should also add in the documentation that the logo should be less that 64 KB. 
Size 200x200 px can sometimes be over this value; depending of the complexity of the logo, so it's good to know upfront. 
Thank you.

**Review by elrondangels — COMMENTED** [review]
Done. 
New files were uploaded in corresponding token folder and following the latest requirements from the new documentation. 
Thank you.

**Comment by elrondangels** [comment]
Hi Guys, 
Any chance to get this moving, please? 
I think it's all in order now. 
Also ANGELS-11b373 by gsworks85 · Pull Request #617 · ElrondNetwork/assets

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
ANGELS-11b373 by gsworks85 · Pull Request #617 · ElrondNetwork/assets

Hi Elrond Team, This is for branding the ANGELS-11b373 NFT collection. Thank you.
 |

 |

 |



Thank you. Elrond Angels Team

    On Wednesday, July 13, 2022 at 04:52:12 PM GMT+3, Alexandru Pislariu ***@***.***> wrote:  
 
 


Hello!
Please check our updated documentation and upload files according to it.

**Comment by elrondangels** [comment]
Hi Team, @SeverMM @AlexandruPislariu, 
Any chance we can get this merged, please? 
Thank you.

**Comment by elrondangels** [comment]
Hey guys, any updates on this one, please? 
It got staled for so much time...
Do let us know if there's anything we need to do/change to get this through. 
Much appreciated your action/reply. 
Thank you. 
Silviu - Elrond Angels.

**Pull request closed without merging**
