### PR TITLE
ADD ART-bc701b

### PR DESCRIPTION
**Pull request by cuben90**
new file:   ART-bc701b/LOGO.svg
	new file:   ART-bc701b/info.json
        new file:   ART-bc701b/LOGO.png

### CODE REVIEW

**Comment by arelrond** [comment]
Hello! Please try to get some more holders, transactions & community - we will be happy to revisit this PR after you do.

Good luck!

**Comment by cuben90** [comment]
Hello,

Thank you for getting back to me. Some time passed, and we now have more
transactions, but it may still be small compared to some other ESDT.

We are an artistic NFT project meant to craft unique collectible NFT coins
in 3D and ultraHD. We have launched two collections so far:
- Act I :  12 coins, total supply 499
- Act II: 15 coins, total supply 800
Coins come in different shapes, alloys and rarities.
As you can see, we have very low supplies compared to other NFT projects in
the Elrond sphere. Scarcity is the essence of our collections.
Our coins holders earn weekly $art amounts. And they can increase their
$art earnings by completing coins sets or families.
More details :
Act II Families
<https://cdn.discordapp.com/attachments/942466316063867051/964588195490721915/ARTCOINER_ACT2_FAMILY_2K.jpg>
Act II Sets
<https://cdn.discordapp.com/attachments/942466316063867051/964588195335512074/ARTCOINER_ACT2_SETS_2K.jpg>
$Art weekly rewards
<https://docs.google.com/spreadsheets/d/e/2PACX-1vQCV_USdLk2tZd90gUME9R8CIgx2A5bwYdtoMe2nvObkPjJNkXymkJkZeuxeaMAI5PERUgf1CNHegrj/pubhtml>

Using their earned $art, our holders will be able to mint our next
collections using $art OR $egld. It’s a way to reward and retain our
holders while removing the standard whitelist system commonly used by NFT
projects.

Consequently to how we built this project and its rules, our holders base
is mechanically limited.
However, we are a serious and passionate project. And we want the $art
token to reflect those values. We want our holders to feel safe when they
receive their $art airdrops. That’s why we want to complete the token’s
whitelist process and no longer be displayed as a « potential scam » on
maiar wallet.

Please, do not hesitate to ask me any question you could have.
I’ll be glad to give you more details on our project.

Have a good day.
Best regards,

Benjamin

**Comment by cuben90** [comment]
Hello,
Did you have the opportunity to review our application again please?
Best regards,

**Comment by cuben90** [comment]
Hi Sever,

You closed the PR, does that mean our application to get our token
whitelisted is approved or not ?

Nobody answered my last emails ^^'
I can provide more info if required.

Please find the body of my last mail bellow :

Hello,

Thank you for getting back to me. Some time passed, and we now have more
transactions, but it may still be small compared to some other ESDT.


We are an artistic NFT project meant to craft unique collectible NFT coins
in 3D and ultraHD. We have launched two collections so far:
- Act I :  12 coins, total supply 499
- Act II: 15 coins, total supply 800
Coins come in different shapes, alloys and rarities.
As you can see, we have very low supplies compared to other NFT projects in
the Elrond sphere. Scarcity is the essence of our collections.
Our coins holders earn weekly $art amounts. And they can increase their
$art earnings by completing coins sets or families.
More details :
Act II Families
<https://cdn.discordapp.com/attachments/942466316063867051/964588195490721915/ARTCOINER_ACT2_FAMILY_2K.jpg>
Act II Sets
<https://cdn.discordapp.com/attachments/942466316063867051/964588195335512074/ARTCOINER_ACT2_SETS_2K.jpg>
$Art weekly rewards
<https://docs.google.com/spreadsheets/d/e/2PACX-1vQCV_USdLk2tZd90gUME9R8CIgx2A5bwYdtoMe2nvObkPjJNkXymkJkZeuxeaMAI5PERUgf1CNHegrj/pubhtml>

Using their earned $art, our holders will be able to mint our next
collections using $art OR $egld. It’s a way to reward and retain our
holders while removing the standard whitelist system commonly used by NFT
projects.

Consequently to how we built this project and its rules, our holders base
is mechanically limited.
However, we are a serious and passionate project. And we want the $art
token to reflect those values. We want our holders to feel safe when they
receive their $art airdrops. That’s why we want to complete the token’s
whitelist process and no longer be displayed as a « potential scam » on
maiar wallet.


Please, do not hesitate to ask me any question you could have.
I’ll be glad to give you more details on our project.

Have a good day.
Best regards,

Benjamin


Le lun. 11 juil. 2022, 22:00, Sever Moldovean ***@***.***> a
écrit :

**Review by SeverMM — CHANGES_REQUESTED** [review]
I love your spirit. This is how the world moves forward. Please change LOGO to logo and resubmit, it will go through 👌

**Comment by AlexandruPislariu** [comment]
Hello!
Please upload a smaller PNG logo file (the limit is 100KB for performance reasons).

**Comment by cuben90** [comment]
Hi Alexandru,

Thank you.
The provided PNG logo file is less than 25KB, it should be good.
But the verification script seems to complain about the size 1000*1000,
what's the supported size please ? I'll request a new format to our
illustrator.

Best regards,
Benjamin

**Comment by AlexandruPislariu** [comment]
The JSON file is invalid, please check it with a tool like https://jsonlint.com/ and commit again.

**Comment by cuben90** [comment]
there was a wrong coma in the json, can you re run the checks please ? 🙏

**Comment by cuben90** [comment]
Hi,

Do you need something more from me now that all the checks are good ?
Have a good weekend.

Best regards,
Benj

**Pull request closed without merging**
