### PR TITLE
Add  ODIN-4d429b

### PR DESCRIPTION
**Pull request by OdinDefiProtocol**
Update logo, description and socials

### CODE REVIEW

**Comment by OdinDefiProtocol** [comment]
Is everything correct?

**Comment by arelrond** [comment]
I can't seem to be able to find the info.json file or the logos (.png or .svg).

**Comment by OdinDefiProtocol** [comment]
.PNG Logo

**Comment by OdinDefiProtocol** [comment]
Logo.PNG
LOGO

**Comment by OdinDefiProtocol** [comment]
Logo.svg
Logo

**Pull request closed without merging**
