### PR TITLE
add SRB-61daf7 NFT

### PR DESCRIPTION
**Pull request by BalooSuperRareBears**

### CODE REVIEW

**Review by janniksam — COMMENTED** [review]
Are you sure you want to start Collection with an upper case C?

**Comment by BalooSuperRareBears** [comment]
Yes. Thanks!

**Comment by arelrond** [comment]
Hello!

Please update the branch so it is up-to-date with the base branch and I will review afterwards.

"This branch is out-of-date with the base branch
Merge the latest changes from master into this branch."

Thanks!

**Comment by BalooSuperRareBears** [comment]
Hello, arelrond

Everything should be ok now, please take a look.

Thanks!

**Review by arelrond — APPROVED** [review]

**Pull request merged**
