### PR TITLE
Add CPA-97530a

### PR DESCRIPTION
**Pull request by grenderro**
Add CPA token information
logo

### CODE REVIEW

**Comment by grenderro** [comment]
logo

**Comment by grenderro** [comment]
Hi
There is anything I need to add to PR?
Warm Regards
Ciprian

**Comment by SeverMM** [comment]
image
Hey there, there is this error: 

This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
logo.png
logo.svg

Also you are trying to add 4 files, please only add info.json, logo.png and logo.svg

**Comment by grenderro** [comment]
logo
logo

**Comment by grenderro** [comment]
`{
    "website": "https://artcpaclub.com/",
    "description": "$CPA will be the fuel to power our Marketplace and DEX, built on the Elrond Blockchain", "ledgerSignature": "",
    "social": {
        "email": "admin@artcpaclub.com",
        "twitter": "https://twitter.com/_Official_CPA",
	"discord": "https://discord.gg/t58ZhW688j",
	"telegram": "https://t.me/+l3Fjd2bULflhZmY0",
        "whitepaper": "https://artcpaclub.com/whitepaper/",
        
    "status": "active"
}`

**Comment by grenderro** [comment]
Hi, done it.
Should be ok.
Thank you for your time

**Review by SeverMM — CHANGES_REQUESTED** [review]
Hey there, the file conflict is still not solved.

**Review by SeverMM — APPROVED** [review]

**Review by SeverMM — CHANGES_REQUESTED** [review]
Please create a folder called "CPA-97530a" (your token ID) and move your project's file there (info.json, logo.svg, logo.png)

**Comment by grenderro** [comment]
Done, created a new folder and moved all files there. There is left only one logo.png which I cannot move or delete.
Thank you for your time.
Warm Regards

**Review by SeverMM — APPROVED** [review]

**Pull request merged**
