### PR TITLE
Plata NFTs

### PR DESCRIPTION
**Pull request by serban-marius**
Plata NFTs Branding!

### CODE REVIEW

**Review by arelrond — DISMISSED** [review]

**Comment by arelrond** [comment]
Hello @serban-marius - please look into the issue above.

Once fixed, I will review again and move forward with the approval process.

Thank you!

**Comment by serban-marius** [comment]
@arelrond Could you try again? Now they are smaller!
Thanks!

**Review by arelrond — APPROVED** [review]

**Comment by arelrond** [comment]
@serban-marius - the files have to be 100KB max.

**Comment by serban-marius** [comment]
@arelrond All .svg fixed & under 100KB. Sorry for the trouble!
Thanks!

**Review by arelrond — APPROVED** [review]

**Pull request merged**
