### PR TITLE
Rename CPA-97530a/info.json to tokens/CPA-97530a/info.json

### PR DESCRIPTION
**Pull request by grenderro**

### CODE REVIEW

**Review by SeverMM — CHANGES_REQUESTED** [review]
Please also add the logo.png and logo.svg files in the tokens/CPA-97530a folder

**Comment by grenderro** [comment]
When trying to move them it says that the files already exists

**Comment by grenderro** [comment]
All done now

**Comment by grenderro** [comment]
> Please also add the logo.png and logo.svg files in the tokens/CPA-97530a folder

All done, hopefully happy days from now on :)

**Review by SeverMM — CHANGES_REQUESTED** [review]
The .json file check failed...

✗ /github/workspace/tokens/CPA-97530a/info.json
SyntaxErrorUnexpected end of JSON input

**Comment by grenderro** [comment]
> The .json file check failed...
> 
> ✗ /github/workspace/tokens/CPA-97530a/info.json SyntaxErrorUnexpected end of JSON input

Sorted. My bad 😢

**Pull request closed without merging**
