### PR TITLE
Add MARE-63e515 [Mainnet]

### PR DESCRIPTION
**Pull request by pupisor**
Requesting brand update for MARE token.
 - [x] Info added
 - [x] png logo added
 - [x] svg logo added

### CODE REVIEW

**Comment by arelrond** [comment]
Hello @pupisor - please remove the comma after "telegram_EN": "https://t.me/Mare_Om_ONG" (,) and commit the changes again.

Thank you!

**Review by pupisor — COMMENTED** [review]
removed comma

**Comment by pupisor** [comment]
what is the problem with logo file?

**Review by arelrond — APPROVED** [review]

**Comment by pupisor** [comment]
"This branch has conflicts that must be resolved" can someone tell me where is the problem?
Screenshot_20220311-213737_Samsung Internet

**Pull request closed without merging**
