### PR TITLE
Add MANY-39af2c branding.

### PR DESCRIPTION
**Pull request by schmitzt3**

### CODE REVIEW

**Comment by SeverMM** [comment]
Please merge the latest version of the master repo into your branch and resubmit.

image

**Comment by tannerhallman** [comment]
@SeverMM Hi that was completed. Do we need to do it again since master has changed?

**Comment by tannerhallman** [comment]
@SeverMM anything we need to do here?

**Comment by schmitzt3** [comment]
@arelrond why was this closed?

**Comment by tannerhallman** [comment]
@arelrond any updates on this?

**Comment by arelrond** [comment]
Please reopen this in a new PR and tag me once done.

**Pull request closed without merging**
