### PR TITLE
added info.json and logo for GRM-0f4614

### PR DESCRIPTION
**Pull request by novakalexandru**

### CODE REVIEW

**Review by quentinpuzenat — APPROVED** [review]

**Review by novakalexandru — COMMENTED** [review]
Please accept our request;)

**Comment by SeverMM** [comment]
Please add the logo in .svg format as well, thank you.

**Comment by novakalexandru** [comment]
Hello Sever, i added 

> Please add the logo in .svg format as well, thank you.

Hello Sever, 

I added the logo in .svg format.

Thanks for your help :)

**Comment by SeverMM** [comment]
Great, now please also name it logo.svg, as per the procedure. Thanks!

**Comment by novakalexandru** [comment]
> Great, now please also name it logo.svg, as per the procedure. Thanks!

really sorry :) updated.

**Comment by novakalexandru** [comment]
updated the json file.

**Comment by novakalexandru** [comment]
:) is ok now?

**Pull request closed without merging**
