### PR TITLE
MPH-f8ea2b

### PR DESCRIPTION
**Pull request by MORPHtok**

### CODE REVIEW

**Comment by arelrond** [comment]
Hello @MORPHtok - please follow the guidelines here: https://elrond.com/blog/branding-esdt-tokens-nft-collections/

- logo does not have to resemble Elrond/Maiar logos, so it doesn’t create confusion in the community
- PR files need to be named info.json, logo.svg and logo.png
- the PR title has to be the token name + identifier (ex: TOKEN-458bbf)
- projects need to have a minimum of 1000 token holders and token transactions
- projects need to have a minimum of 1000+ Twitter, Discord or TG official channel followers
- projects need to have a working website
- max pic size 100kb (.png, .jpg)

I am not able to find a Twitter/Discord or TG channel with 1000+ followers or a working website for your project.

**Comment by MORPHtok** [comment]
Hello,

This should not be an issue since as stated in your blog these guidelines are not mandatory requirements : 

"Please follow the guidelines below to **maximize the chances** of passing through the filters, which are in place to create a healthy and sustainable token ecosystem:"

MPH token is almost 1 year old (one of the oldest token), more than 1,5k holders (in top 100) and listed on the main P2P exchange jexchange.

Regards

Sja

**Comment by MORPHtok** [comment]
@arelrond Hello,

Can we expect to move forward on this PR today ?

Regards

sja

**Comment by MORPHtok** [comment]
@arelrond @ioandanpopa 
Dear both,
Do you have some good news about this antediluvian PR ?
Can we proceed with the validation ?

Regards
Sja

**Review by arelrond — APPROVED** [review]

**Pull request merged**
