### PR TITLE
Add WHALE-b018f0

### PR DESCRIPTION
**Pull request by KingDavidMAIAR**
[Logo Whale v2](https://github.com/KingDavidMAIAR/WHALE-b018f0/blob/main/Logo%20Whale%20v2.png)

[Logo Whale v2](https://github.com/KingDavidMAIAR/WHALE-b018f0/blob/main/Logo%20Whale%20v2.svg)

### CODE REVIEW

**Comment by KingDavidMAIAR** [comment]
Add me please :)

**Comment by arelrond** [comment]
Please use a different logo - this is just the Maiar logo turned upside down, in yellow.

Thank you!

**Comment by KingDavidMAIAR** [comment]
Hello Alex, 
Ok thanck you for your feed back.
I have change the logo with a new version for 2022.
You can show in my repositories https://github.com/KingDavidMAIAR/WHALE-b018f0

**Comment by KingDavidMAIAR** [comment]
[](url[)](https://github.com/KingDavidMAIAR/WHALE-b018f0/blob/main/Logo%20Whale%20v2.png)

**Comment by KingDavidMAIAR** [comment]
Logo Whale v2
Logo Whale v2

**Comment by KingDavidMAIAR** [comment]
Hello,
Up please :)
Thx

**Comment by KingDavidMAIAR** [comment]
Hello,
I have no reponse why ? help me please ?

**Pull request closed without merging**
