### PR TITLE
add TOC-56f783 token to branding request

### PR DESCRIPTION
**Pull request by remiconext**
Can you make a branding of this please. Thanks

### CODE REVIEW

**Comment by remiconext** [comment]
The id of the token is TOC-56f783

**Comment by guilezrance** [comment]
@SeverMM Is everything correct?

**Comment by guilezrance** [comment]
@LucianMincu Can you tell me more about what is blocking in this PR plz?

**Comment by guilezrance** [comment]
@SeverMM Can you tell me what is blocking on this PR plz?

**Review by guilezrance — APPROVED** [review]

**Pull request closed without merging**
