### PR TITLE
olimp token

### PR DESCRIPTION
**Pull request by anuarbek94**

### CODE REVIEW

**Review by bmcdeveloper01 — APPROVED** [review]

**Review by bmcdeveloper01 — APPROVED** [review]

**Review by bmcdeveloper01 — APPROVED** [review]
good project

**Review by bmcdeveloper01 — APPROVED** [review]
good project

**Review by anuarbek94 — COMMENTED** [review]
up

**Comment by anuarbek94** [comment]
guys, help to fix the problem @BeniaminMincu

**Comment by arelrond** [comment]
Hello @anuarbek94 - your application is incomplete. 

Please follow the steps here: https://docs.elrond.com/developers/esdt-tokens/#branding

It looks like you are missing logo.svg and the token unique identifier (the random numbers and letters after the token ticker)

**Comment by anuarbek94** [comment]
> Hello @anuarbek94 - your application is incomplete.
> 
> Please follow the steps here: https://docs.elrond.com/developers/esdt-tokens/#branding
> 
> It looks like you are missing logo.svg and the token unique identifier (the random numbers and letters after the token ticker)

it's done now

**Pull request closed without merging**
