### PR TITLE
Create SFT-a55e3e

### PR DESCRIPTION
**Pull request by BaekM2**
logo

### CODE REVIEW

**Comment by BaekM2** [comment]
logo

**Comment by BaekM2** [comment]
{
  "website": "https://www.safetime.in",
  "description": "SafeTime is the currency that wants to save you time by implementing a new system.The people of our community will benefit from a wide range of people who are professional in coin analysis, finding scam tokens, investing in a single package that contains several tokens as low as possible.",
  "social": {
    "email": "contact@safetime.in",
    "twitter": "https://twitter.com/SafetimeSft"
  },
  "status": "active"
}

**Review by BaekM2 — COMMENTED** [review]
#508

**Review by BaekM2 — COMMENTED** [review]
logo

**Comment by arelrond** [comment]
Please follow the guidelines here and resubmit the PR correctly: https://elrond.com/blog/elrond-web-tools-token-branding/

**Pull request closed without merging**
