### PR TITLE
SUPER-764d8d

### PR DESCRIPTION
**Pull request by michavie**
this PR includes brand info & assets for Superciety's SUPER token (SUPER-764d8d).

i'd also like to request full compatibility with ledger services via a signature `ledgerSignature` provided from Elrond as stated in the readme.

additional info:
- images follow a size of 198x198px, derived from existing logos
- images have been optimized for reduced file size

update:
to increase trust & transparency we published an easily accessible tokenomics overview + analytics: https://superciety.com/analytics

### CODE REVIEW

**Comment by elnicos** [comment]
Hellow
Nice project

**Comment by andrei-x1** [comment]
:+1:

**Comment by Al3xander05** [comment]
$SUPER professional and welcoming team behind this project! Definitely worth checking it out!

**Comment by VisanM** [comment]
Is there any missing info on this MR ? or is there any reason why is not merged ? I see there is no whitepaper link attached

**Review by SeverMM — APPROVED** [review]

**Pull request merged**
