### PR TITLE
HETOnetwork token branding HETO-663cf8

### PR DESCRIPTION
**Pull request by Hetofinance**
{
    "website": "https://www.hetofinance.com",
    "description": "HETO is a decentralized services powering hybrid smart contract use instances throughout a huge-sort of industries",
    "social": {
        "email": "Hetofinance@gmail.com",
        "discord": "https://discord.gg/xX83j5J4m6",
        "twitter": "https://twitter.com/heto_finance",
        "whitepaper": "https://hetofinance.com/php_assets/uploads/2022/03/HETO-FINANCE-2.pdf",    
    },
    "status": "active"
}
258FA1F1-A7D4-4D88-8F7B-70FDCA933CA2

36E21158-4B61-46E9-B9EC-F6499282DB2C 2

### CODE REVIEW

**Comment by Hetofinance** [comment]
-4B61-46E9-B9EC-F6499282DB2C
### 

258FA1F1-A7D4-4D88-8F7B-70FDCA933CA2

**Review by Hetofinance — COMMENTED** [review]
258FA1F1-A7D4-4D88-8F7B-70FDCA933CA2

**Review by SeverMM — CHANGES_REQUESTED** [review]
Please add the files with the correct names: info.json, logo.png, logo.svg, do not add other files.

**Comment by Hetofinance** [comment]
> Please add the files with the correct names: info.json, logo.png, logo.svg, do not add other files.

Here is the link to the new PR 
https://github.com/ElrondNetwork/assets/pull/319/files

**Pull request closed without merging**
