### PR TITLE
 add brand support for NFTIM-4586ac collection

### PR DESCRIPTION
**Pull request by marqbeniamin**

### CODE REVIEW

**Review by arelrond — APPROVED** [review]

**Review by arelrond — APPROVED** [review]

**Comment by arelrond** [comment]
@marqbeniamin - looks like there's another issue. Please review.

Thanks!

**Comment by marqbeniamin** [comment]
image

**Review by arelrond — APPROVED** [review]

**Comment by arelrond** [comment]
@marqbeniamin - I'll check with the devs and I'll get back to you once I have more details.

**Comment by estargames** [comment]
We have the same issues on the ESTAR-afaaf0 folder.

**Comment by marqbeniamin** [comment]
I think this is a problem for build.
I created a new PR here: https://github.com/ElrondNetwork/assets/pull/728

**Pull request merged**
