### PR TITLE
Sing-35e8da

### PR DESCRIPTION
**Pull request by SingCrypto**

### CODE REVIEW

**Comment by LucianMincu** [comment]
Two of your files includes a spaces in their naming.

Please rename the logo files accordingly to the standard process. 🙏

**Review by LucianMincu — CHANGES_REQUESTED** [review]
Tests are failing.

Two of your files includes a spaces in their naming.

Please rename the logo files accordingly to the standard process. 🙏

**Comment by SingCrypto** [comment]
Ok

**Review by LucianMincu — CHANGES_REQUESTED** [review]
the following two files needs to be renamed like this:

from `SING-35e8da - logo 200x200 png.png` to `logo.png`
and `tokens/SING-35e8da/SING-35e8da - logo 200x200 svg.svg` to `logo.svg`

**Pull request closed without merging**
