### PR TITLE
BPCT-bb5459

### PR DESCRIPTION
**Pull request by macbenouze**
Le BPC Token est utilisé pour le programme de fidélité BPC Triathlon Coaching

### CODE REVIEW

**Comment by macbenouze** [comment]
11029563_811895245551843_5716679651513096864_n (4)

**Review by jszatanek — APPROVED** [review]
Change ok !

**Review by jszatanek — APPROVED** [review]
File change ok !

**Review by jszatanek — CHANGES_REQUESTED** [review]
I think you need to add your token logo files:
- logo.png
- logo.svg
in the pull request

**Comment by macbenouze** [comment]
BPC-LOGO-NOIR-2

**Comment by macbenouze** [comment]
BPC-LOGO-NOIR

**Comment by jszatanek** [comment]
It's not ok :) the logo files need to be added to a commit in this pull request

**Review by SeverMM — CHANGES_REQUESTED** [review]
Hey there, please create a folder with your exact token name & ID, and place the content of this file in info.json, then make sure to also add your icon in .png and .svg format. Good luck

**Pull request closed without merging**
