### PR TITLE
 RARE-99e8b0 Token Branding 

### PR DESCRIPTION
**Pull request by SuperRareBears**
Opening PR to add branding for  
RARE-99e8b0 which is the token for SRB collection, RARE is a token which is used within the SuperRareBears ecosystem, an NFT project built on Elrond. Usecase includes NFT sales, staking rewards & governance
See
https://medium.com/@superrarebears/srb-rarenomics-esdt-token-rare-distribution-v3-a2cf8b0e7090

### CODE REVIEW

**Review by arelrond — APPROVED** [review]

**Comment by arelrond** [comment]
Hello @SuperRareBears - please take a look at the issues above and let me know once fixed so I can approve and merge.

Thanks!

**Comment by BalooSuperRareBears** [comment]
> 

Hello, @arelrond - our branch should be up to date with master now and I've commit a small change to try to re-trigger all the checks. Please let us know if everything is ok now. Thanks!

**Comment by SeverMM** [comment]
Please do what Alex said, your brach is still out of date:
image

**Review by SeverMM — APPROVED** [review]

**Comment by SuperRareBears** [comment]
Appreciate the help 🙌🐻🐾

**Pull request merged**
